language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint
  - make

script:
  - go test -cpu=1,2 -v -tags integration ./...