language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

env:
  - GO111MODULE=on
  - SG_CONFIG=configs/config.yml

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -cpu=1,2 -v -tags integration ./...