version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: go get -v -d ./...
      - run: go test -v -tags integration ./...
      - run: make

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: ./target/
