---
host: "127.0.0.1"
port: 3000
uri-schema: "http://"
version: "v1"
api-key: "test"

database:
  file: "data.db"
  auto-migrate: true

remote:
  address: "http://localhost:8000/graphql"
  # this should be the profile corresponding to the API key
  profile-id: 1

log:
  formatter: "text"
  level: "debug"
